services:
  - type: web
    name: reszvault
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://reszvault.vercel.app
      - key: BACKEND_PUBLIC_URL
        value: https://reszvault.onrender.com
      - key: GROQ_MODEL
        value: openai/gpt-oss-20b
      - key: GROQ_API_URL
        value: https://api.groq.com/openai/v1/chat/completions
      - key: GROQ_API_KEY
        sync: false
